# Generated by Django 5.1.3 on 2025-01-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0020_course_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseFeedback',
        ),
    ]
